/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // START
    {
      type: 'html',
      value: '<div class="sidebar__section">START</div>',
      defaultStyle: true,
    },
    'intro',

    // FEATURED
    {
      type: 'html',
      value: '<div class="sidebar__section">FEATURED</div>',
      defaultStyle: true,
    },

    // Featured: GitHub API Docs (manual, com tudo aberto)
    {
      type: 'category',
      label: 'GitHub API Docs',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Guides & Fundamentals',
          collapsible: true,
          collapsed: false,
          items: [
            'github-api-doc/guides/overview',
            'github-api-doc/guides/quick-start',
            'github-api-doc/guides/authentication',
            'github-api-doc/guides/pagination',
            'github-api-doc/guides/errors-and-status-codes',
            'github-api-doc/guides/validation-and-sources',
          ],
        },
        {
          type: 'category',
          label: 'API Reference',
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: 'category',
              label: 'Endpoints',
              collapsible: true,
              collapsed: false,
              items: ['github-api-doc/reference/endpoints/list-issues'],
            },
          ],
        },
      ],
    },

    // PROFILE
    {
      type: 'html',
      value: '<div class="sidebar__section">PROFILE</div>',
      defaultStyle: true,
    },

    // About
    {
      type: 'category',
      label: 'About',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'about-me' }],
    },

    // Case Studies
    {
      type: 'category',
      label: 'Case Studies',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'case-studies' }],
    },

    // SAMPLES
    {
      type: 'html',
      value: '<div class="sidebar__section">SAMPLES</div>',
      defaultStyle: true,
    },

    // Documentation Samples
    {
      type: 'category',
      label: 'Documentation Samples',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'documentation-samples' }],
    },
  ],
};

module.exports = sidebars;
