/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // Home
    'intro',

    // Featured: GitHub API Docs (manual, com tudo aberto)
    {
      type: 'category',
      label: 'GitHub API Docs',
      collapsible: true,
      collapsed: false, // <-- abre esse bloco automaticamente
      items: [
        {
          type: 'category',
          label: 'Guides & Fundamentals',
          collapsible: true,
          collapsed: false, // <-- abre automaticamente
          items: [
            'github-api-doc/guides/overview',
            'github-api-doc/guides/quick-start',
            'github-api-doc/guides/authentication',
            'github-api-doc/guides/pagination',
            'github-api-doc/guides/errors-and-status-codes',
            'github-api-doc/guides/validation-and-sources',
          ],
        },
        {
          type: 'category',
          label: 'API Reference',
          collapsible: true,
          collapsed: false, // <-- abre automaticamente
          items: [
            {
              type: 'category',
              label: 'Endpoints',
              collapsible: true,
              collapsed: false, // <-- abre automaticamente
              items: [
                'github-api-doc/reference/endpoints/list-issues',
              ],
            },
          ],
        },
      ],
    },

    // About
    {
      type: 'category',
      label: 'About',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'about-me' }],
    },

    // Case Studies
    {
      type: 'category',
      label: 'Case Studies',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'case-studies' }],
    },

    // Samples
    {
      type: 'category',
      label: 'Documentation Samples',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'documentation-samples' }],
    },
  ],
};

module.exports = sidebars;
